import { getCategories } from "../../lib/db";
import { familyFallback } from "../../lib/catalogue";
import { SiteHeader, SiteFooter } from "../../components/SiteChrome";

export const metadata={title:"Marriage, Family & Community"};

export default async function MarriageFamily(){
  const dbCategories = await getCategories("marriage_family_community");
  const categories = dbCategories.length ? dbCategories : familyFallback;
  return <main><SiteHeader/><section className="section-hero"><div className="section-hero-inner"><div><p className="kicker light">02 · FAMILY</p><h1>Marriage, Family <em>& Community</em></h1><p>A practical learning journey through marriage traditions, family systems, preparation, care, cultural guidance and community responsibilities.</p></div><div className="hero-path compact"><p className="kicker light">LEARNING JOURNEY</p><div><span>01</span><strong>Understand marriage traditions</strong></div><div><span>02</span><strong>Explore family systems and care</strong></div><div><span>03</span><strong>Prepare for shared responsibilities</strong></div></div></div></section><section className="section-content"><div className="section-heading-row"><div><p className="kicker">02 · KNOWLEDGE AREAS</p><h2>Explore the <em>family journey</em></h2></div></div><div className="learning-cards">{categories.map((x,i)=><a className="learning-card" key={x.slug} href={x.slug === "marriage-preparation-readiness" ? "/marriage-family/readiness" : `/marriage-family/${x.slug}`}><span>{String(i+1).padStart(2,"0")}</span><div><small>EXPLORE</small><h3>{x.name}</h3><p>{x.description ?? "Explore documented knowledge, practical preparation and cultural context."}</p></div><b>→</b></a>)}</div></div></section><section className="learning-band"><div className="section-shell"><p className="kicker light">CONTEXT MATTERS</p><h2>Respect tradition.<br/><em>Make room for difference.</em></h2><p>Zambian marriage and family practices vary across cultural groups, families and circumstances. Mwambo presents that context rather than reducing it to one rule.</p></div></section><SiteFooter/></main>
}