import { getPublishedEntry, getEntrySources } from "../../../lib/db";
import { familyKnowledgeFallback } from "../../../lib/catalogue";
import { notFound } from "next/navigation";
import { SiteHeader, SiteFooter } from "../../../components/SiteChrome";

export default async function KnowledgeEntryPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;
  const dbEntry=await getPublishedEntry(slug);
  const fallback=familyKnowledgeFallback.find(x=>x.slug===slug);
  if(!dbEntry&&!fallback)notFound();
  if(fallback&&!dbEntry){
    return <main><SiteHeader/><section className="detail-hero"><div className="section-shell"><a className="back back-light" href="/marriage-family">← Marriage, Family & Community</a><p className="kicker light">SOURCE-BASED KNOWLEDGE</p><h1>{fallback.title}</h1><p>{fallback.summary}</p></div></section><section className="knowledge-layout"><article className="knowledge"><div className="knowledge-section"><p className="kicker">01 · KNOWLEDGE</p><h2>What the record tells us</h2><p>{fallback.content}</p></div>{fallback.contemporary_context&&<div className="knowledge-section"><p className="kicker">02 · CONTEXT</p><h2>Contemporary context</h2><p>{fallback.contemporary_context}</p></div>}{fallback.variation_notes&&<div className="knowledge-section"><p className="kicker">03 · VARIATION</p><h2>Regional and cultural context</h2><p>{fallback.variation_notes}</p></div>}<section className="sources knowledge-section"><p className="kicker">04 · SOURCES</p><h2>Sources & provenance</h2>{fallback.sources.map((source,i)=><div className="source" key={source.title}><span>{String(i+1).padStart(2,"0")}</span><strong>{source.title}</strong><p>{source.publisher}{source.year?" · "+source.year:""}</p><p>{source.citation}</p><a href={source.url} target="_blank" rel="noreferrer">Read original source ↗</a></div>)}</section></article></section><SiteFooter/></main>;
  }
  const entry=dbEntry!;
  const sources=await getEntrySources(entry.id);
  return <main><SiteHeader/><section className="detail-hero"><div className="section-shell"><a className="back back-light" href="/marriage-family">← Marriage, Family & Community</a><p className="kicker light">VERIFIED KNOWLEDGE</p><h1>{entry.title}</h1>{entry.summary&&<p>{entry.summary}</p>}</div></section><section className="knowledge-layout"><article className="knowledge"><div className="knowledge-section"><p className="kicker">01 · KNOWLEDGE</p><h2>What the record tells us</h2><p>{entry.content}</p></div>{entry.historical_context&&<div className="knowledge-section"><p className="kicker">02 · CONTEXT</p><h2>Historical context</h2><p>{entry.historical_context}</p></div>}{entry.contemporary_context&&<div className="knowledge-section"><p className="kicker">03 · CONTEXT</p><h2>Contemporary context</h2><p>{entry.contemporary_context}</p></div>}{entry.variation_notes&&<div className="knowledge-section"><p className="kicker">04 · VARIATION</p><h2>Regional and cultural context</h2><p>{entry.variation_notes}</p></div>}<section className="sources knowledge-section"><p className="kicker">05 · SOURCES</p><h2>Sources & provenance</h2>{sources.length?sources.map((source,i)=><div className="source" key={source.id}><span>{String(i+1).padStart(2,"0")}</span><strong>{source.title}</strong>{source.publisher&&<p>{source.publisher}{source.publication_year?" · "+source.publication_year:""}</p>}<p>{source.citation}</p>{source.relevance_note&&<p>{source.relevance_note}</p>}{source.url&&<a href={source.url} target="_blank" rel="noreferrer">Read original source ↗</a>}</div>):<p>Source records will appear here as the entry completes editorial review.</p>}</section></article></section><SiteFooter/></main>
}