import Link from "next/link";
import { getEditorialEntry, getEntrySourceIds, getReviewHistory } from "../../../../lib/editorial";
import { notFound } from "next/navigation";
import { transitionEntry } from "../../actions";
import { requireEditorialUser } from "../../../../lib/editorial-auth";

export default async function EntryDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const [entry, sourceIds, history, user] = await Promise.all([getEditorialEntry(id), getEntrySourceIds(id), getReviewHistory(id), requireEditorialUser()]);
  if (!entry) notFound();
  return <main className="simple admin"><div className="admin-nav"><strong>MWAMBO EDITORIAL</strong><Link href="/admin/entries">Entries</Link></div><p className="eyebrow">{entry.status.replace("_"," ").toUpperCase()}</p><h1>{entry.title}</h1><p className="lead">{entry.summary}</p><div className="admin-meta"><span>{entry.category_name ?? "Uncategorised"}</span><span>Updated {new Date(entry.updated_at).toLocaleString()}</span></div><article className="knowledge"><div><h2>Knowledge</h2><p>{entry.content}</p></div>{entry.historical_context && <div><h2>Historical context</h2><p>{entry.historical_context}</p></div>}{entry.contemporary_context && <div><h2>Contemporary context</h2><p>{entry.contemporary_context}</p></div>}{entry.variation_notes && <div><h2>Variation / regional context</h2><p>{entry.variation_notes}</p></div>}<div><h2>Sources attached</h2><p>{sourceIds.length ? `${sourceIds.length} source record(s) attached.` : "No sources attached yet."}</p></div></article><section className="workflow"><h2>Workflow</h2><p className="admin-help">Signed in as <strong>{user.display_name ?? user.email ?? "Editorial user"}</strong> · role: <strong>{user.role}</strong></p><div className="workflow-actions">{(["in_review","verified","published","returned","archived"] as const).map((next)=>{const can = next === "in_review" ? ["contributor","reviewer","editor","administrator"].includes(user.role) : next === "verified" ? ["reviewer","editor","administrator"].includes(user.role) : next === "published" ? ["editor","administrator"].includes(user.role) : next === "returned" ? ["reviewer","editor","administrator"].includes(user.role) : ["editor","administrator"].includes(user.role); return can ? <form action={transitionEntry} key={next}><input type="hidden" name="id" value={entry.id}/><input type="hidden" name="new_status" value={next}/><button className="button light" type="submit">{next === "in_review" ? "Submit for review" : next === "verified" ? "Verify" : next === "published" ? "Publish" : next === "returned" ? "Return" : "Archive"}</button></form> : null;})}</div></section><section className="sources"><h2>Review history</h2>{history.length ? history.map((item:any)=><div className="source" key={item.id}><strong>{item.previous_status ?? "new"} → {item.new_status}</strong><p>{item.notes ?? "No note recorded."}</p><small>{new Date(item.created_at).toLocaleString()}</small></div>) : <p>No workflow history yet.</p>}</section></main>;
}
