const heritage=["Zambia at a Glance","Culture & Tradition","Cultural Groups","Chiefs & Chiefdoms","Ceremonies & Festivals","Languages","Cultural Map","Knowledge Library"];
const family=["Zambian Marriages","Marriage Traditions","Family Systems","Marriage Preparation & Readiness","Family Care","Alangizi & Cultural Guidance","Community Values & Responsibilities"];

function Navigation(){return <header className="site-header"><nav className="nav"><a className="brand" href="/">MWAMBO <small>KNOW YOUR ROOTS.</small></a><div className="navlinks"><a href="/heritage">Heritage</a><a href="/marriage-family">Marriage & Family</a><a href="/about">About</a></div><a className="nav-cta" href="/search">Search <span>⌕</span></a><details className="mobile-nav"><summary>Menu</summary><div className="mobile-menu"><a href="/heritage">Heritage</a><a href="/marriage-family">Marriage & Family</a><a href="/about">About</a><a href="/search">Search</a></div></details></nav></header>}

function Journey({items,href}:{items:string[];href:string}){return <div className="journey-list">{items.map((x,i)=><a href={href} className="journey-item" key={x}><span>{String(i+1).padStart(2,"0")}</span><div><small>EXPLORE</small><strong>{x}</strong></div><b>→</b></a>)}</div>}

function Home(){return <main><Navigation/>
<section className="learning-hero"><div className="hero-inner"><div><p className="kicker light">MWAMBO · CULTURAL KNOWLEDGE</p><h1>Know Your Roots.<br/><em>Know Your Zambia.</em></h1><p className="hero-lead">A practical learning journey through Zambia's heritage, traditions, languages, family life and living cultural identity.</p><div className="hero-meta"><span><strong>02</strong> Learning journeys</span><span><strong>15</strong> Knowledge areas</span></div></div><div className="hero-path"><p className="kicker light">YOUR LEARNING JOURNEY</p><div className="path-line"><a href="/heritage"><span>01</span><strong>Heritage & National Identity</strong></a><a href="/marriage-family"><span>02</span><strong>Marriage, Family & Community</strong></a></div></div></div></section>

<section className="intro"><div><p className="kicker">FROM KNOWLEDGE TO UNDERSTANDING</p><h2>Learn it.<br/>Understand it.<br/><em>Carry it forward.</em></h2></div><div><p>Mwambo is designed as a cultural learning journey. Start with the big picture, explore a subject, understand its context and follow the knowledge to its sources.</p><p>Culture is living knowledge. Where practices differ across communities, places or generations, Mwambo makes that context visible.</p></div></section>

<section className="journeys"><div className="section-shell"><div className="section-heading-row"><div><p className="kicker">01 · HERITAGE</p><h2>Heritage & <em>National Identity</em></h2></div><a className="button button-primary" href="/heritage">Start journey →</a></div><Journey items={heritage} href="/heritage"/></div></section>

<section className="journeys journey-alt"><div className="section-shell"><div className="section-heading-row"><div><p className="kicker">02 · FAMILY</p><h2>Marriage, Family <em>& Community</em></h2></div><a className="button button-primary" href="/marriage-family">Start journey →</a></div><Journey items={family} href="/marriage-family"/></div></section>

<section className="learning-focus"><div className="section-shell focus-grid"><div><p className="kicker light">THE MWAMBO STANDARD</p><h2>Show the source.<br/><em>Show the context.</em></h2><p>Published knowledge should identify its source, community or place, historical setting and meaningful variation.</p><a className="button button-yellow" href="/about">Our editorial approach →</a></div><div className="focus-list"><div><span>01</span><p>Human-reviewed cultural knowledge</p></div><div><span>02</span><p>Regional and community variation respected</p></div><div><span>03</span><p>Sources and provenance made visible</p></div><div><span>04</span><p>Designed for learning, not just browsing</p></div></div></div></section>
<footer><strong>MWAMBO</strong><p>Know Your Roots. Know Your Zambia. · © 2026 Mwambo</p></footer></main>}
export default Home;