import { SiteHeader, SiteFooter } from "../../components/SiteChrome";
export const metadata={title:"Privacy Policy"};
export default function PrivacyPolicy(){return <main><SiteHeader/><article className="legal-page"><p className="kicker">MWAMBO · PRIVACY</p><h1>Privacy Policy</h1><p className="legal-lead">Mwambo is committed to handling personal information responsibly, transparently and securely. This policy explains what information we may collect, why we use it, how we protect it and the choices available to you.</p><p className="legal-updated">Last updated: 23 September 2026</p>
<section><h2>1. Who this policy applies to</h2><p>This policy applies to the Mwambo website and related digital services operated under the Mwambo project. It applies when you browse the site, use the marriage readiness assessment, submit information through a Mwambo feature, or otherwise interact with the service.</p></section>
<section><h2>2. Information we may collect</h2><p>Depending on the feature you use, we may process information such as your name, contact details, account information, technical information about your device or browser, and information you voluntarily provide when using a feature.</p><p>The marriage readiness assessment is designed for reflection. Where responses or results are stored, they may reveal information about personal circumstances, including relationship, family or other sensitive matters. We therefore treat such information with appropriate care.</p></section>
<section><h2>3. Why we use information</h2><p>We may use personal information to provide and improve Mwambo services, respond to requests, maintain security, prevent misuse, keep records where necessary, and meet legal or regulatory obligations. We do not sell personal information.</p></section>
<section><h2>4. Lawful and fair processing</h2><p>Mwambo will seek an appropriate lawful basis for processing personal data and will aim to collect only information that is relevant to the stated purpose. Where consent is required, we will ask for it clearly and allow it to be withdrawn where applicable.</p></section>
<section><h2>5. Sharing and disclosure</h2><p>We do not disclose personal information to third parties for their own marketing. Information may be shared with service providers that process information on Mwambo's behalf, where necessary to operate the service, subject to appropriate safeguards. Information may also be disclosed where required or permitted by law.</p></section>
<section><h2>6. Security</h2><p>We use reasonable technical and organisational measures intended to protect personal information against unauthorised access, loss, misuse, alteration or disclosure. No internet service can guarantee absolute security, so users should also protect their account credentials and devices.</p></section>
<section><h2>7. Retention</h2><p>Personal information should not be kept longer than necessary for the purpose for which it was collected, unless a longer period is required or permitted by law. Retention periods may differ depending on the type of information and the service involved.</p></section>
<section><h2>8. Your rights</h2><p>Subject to applicable law, you may have rights relating to access, correction, objection, restriction, portability and erasure of personal data, as well as the right to withdraw consent where processing is based on consent. Requests will be considered in accordance with applicable legal requirements.</p></section>
<section><h2>9. Children</h2><p>Mwambo is not designed to collect personal information from children for purposes that require parental or guardian involvement. Where a feature involves children or information about children, additional safeguards should apply.</p></section>
<section><h2>10. Changes to this policy</h2><p>We may update this policy when the service, technology or applicable legal requirements change. The latest version will be published on this page with its effective or update date.</p></section>
<section><h2>11. Questions and privacy requests</h2><p>For privacy questions or requests concerning information held by Mwambo, please use the official contact channel made available by Mwambo. Requests should include enough information for us to identify the relevant account or interaction without unnecessarily including sensitive information.</p></section>
<div className="legal-reference"><strong>Legal framework</strong><p>This policy is intended to support responsible processing under applicable Zambian law, including the Data Protection Act, 2021 and related regulations. The Act establishes rights for data subjects and duties for data controllers and processors.</p></div>
</article><SiteFooter/></main>}