"use client";

import { useMemo, useState } from "react";

type Question = { id:number; category:string; prompt:string; rationale:string };
const QUESTIONS: Question[] = [
  {id:1,category:"Emotional readiness",prompt:"Can we manage disagreement, disappointment and stress without threats, humiliation or withdrawal?",rationale:"Marriage requires safe ways to handle difficult emotions and conflict."},
  {id:2,category:"Communication",prompt:"Can we discuss important issues honestly, listen to each other and reach workable agreements?",rationale:"Clear communication supports trust and shared decision-making."},
  {id:3,category:"Values and expectations",prompt:"Have we discussed the values, roles and expectations we will bring into married life?",rationale:"Unspoken expectations can become sources of avoidable conflict."},
  {id:4,category:"Financial preparedness",prompt:"Have we discussed income, spending, debt, savings, financial responsibilities and realistic household priorities?",rationale:"Financial transparency helps couples plan responsibly."},
  {id:5,category:"Family and in-laws",prompt:"Have we discussed boundaries, support and responsibilities involving parents, siblings and extended family?",rationale:"Extended family relationships can be important in Zambian family life."},
  {id:6,category:"Cultural understanding",prompt:"Have we discussed how our cultural, ethnic, linguistic and family backgrounds may shape our marriage?",rationale:"Respecting difference is more useful than assuming every family follows one tradition."},
  {id:7,category:"Roles and responsibilities",prompt:"Have we agreed how household work, decision-making, care and major responsibilities will be shared?",rationale:"Practical clarity reduces resentment and uncertainty."},
  {id:8,category:"Children and parenting",prompt:"Have we discussed whether we want children, parenting values, discipline, education and caregiving responsibilities?",rationale:"Parenting expectations should be explored before major commitments."},
  {id:9,category:"Safety, respect and boundaries",prompt:"Do we respect each other's boundaries and have a relationship free from coercion, intimidation and violence?",rationale:"Safety and dignity are foundational; counselling should never be used to excuse abuse."},
  {id:10,category:"Shared future planning",prompt:"Can we identify realistic shared goals for the next five to ten years and discuss how we will work toward them?",rationale:"Shared planning helps translate commitment into practical preparation."}
];

export default function MarriageReadinessAssessment() {
  const [answers,setAnswers]=useState<Record<number,number>>({});
  const [submitted,setSubmitted]=useState(false);
  const result=useMemo(()=>{if(!submitted)return null;const scores=QUESTIONS.map(q=>({category:q.category,score:answers[q.id]??0}));const total=scores.reduce((a,b)=>a+b.score,0);const pct=Math.round(total/(QUESTIONS.length*10)*100);return {scores,pct,strengths:scores.filter(x=>x.score>=8).map(x=>x.category),focus:scores.filter(x=>x.score<=6).map(x=>x.category),tier:pct<40?"Preparation Needed":pct<60?"Further Preparation Recommended":"Positive Readiness Indicators"};},[answers,submitted]);
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(Object.keys(answers).length<QUESTIONS.length){window.alert("Please rate all 10 readiness domains before generating your report.");return;}setSubmitted(true);window.scrollTo({top:300,behavior:"smooth"});};

  if(submitted&&result)return <main className="readiness-page"><a className="back" href="/marriage-family">← Marriage, Family & Community</a><p className="eyebrow">MARRIAGE, FAMILY & COMMUNITY · READINESS</p><div className="readiness-head"><div><h1>{result.tier}</h1><p>A private self-reflection tool. This is not a clinical, legal or professional determination of whether someone is ready for marriage.</p></div><div className="readiness-score"><span>COMPOSITE SCORE</span><strong>{result.pct}%</strong></div></div><div className="readiness-notice">Use the results as a conversation guide. Consider discussing lower-scoring areas with a trusted Alangizi, counsellor or other appropriate adviser. A low score does not make a marriage decision for you.</div><section className="readiness-grid"><div className="readiness-panel"><p className="eyebrow">AREAS TO EXPLORE</p><h2>Topics for further discussion</h2>{result.focus.length?<div className="chips">{result.focus.map(x=><span key={x}>{x}</span>)}</div>:<p>All domains were rated above the focused-discussion threshold. Continue revisiting these conversations as circumstances change.</p>}</div><div className="readiness-panel"><p className="eyebrow">FOUNDATIONAL AREAS</p><h2>Strong indicators</h2>{result.strengths.length?<div className="chips strong">{result.strengths.map(x=><span key={x}>{x}</span>)}</div>:<p>No domain reached the strong-indicator threshold. That is an invitation for further reflection, not a judgment.</p>}</div></section><section className="readiness-panel scorecard"><p className="eyebrow">DOMAIN BREAKDOWN</p><h2>10-domain scorecard</h2>{result.scores.map((x,i)=><div className="score-row" key={x.category}><div><strong>{i+1}. {x.category}</strong><p>{QUESTIONS[i].rationale}</p></div><div className="score-value">{x.score}/10</div></div>)}</section><div className="readiness-actions"><button onClick={()=>{setAnswers({});setSubmitted(false);}}>Retake assessment</button><a href="/marriage-family">Return to Marriage & Family</a></div></main>;

  return <main className="readiness-page"><a className="back" href="/marriage-family">← Marriage, Family & Community</a><p className="eyebrow">SECTION 02 · MARRIAGE PREPARATION & READINESS</p><div className="readiness-intro"><div><h1>Marriage Readiness & Preparedness</h1><p>A confidential self-assessment for reflection before marriage. It explores communication, emotional maturity, finances, family expectations, cultural understanding, safety and practical preparation.</p></div><div className="readiness-meta">10 CORE DOMAINS<br/>1–10 SCALE<br/>SELF-REFLECTION</div></div><div className="readiness-notice">There is no universal score that can determine whether a person or couple should marry. Answer honestly and use the results to identify conversations that deserve more attention.</div><form onSubmit={submit} className="readiness-form">{QUESTIONS.map((q,i)=>{const v=answers[q.id]??0;return <section className="question" key={q.id}><div className="question-title"><span>DOMAIN {i+1}</span><h2>{q.category}</h2><p>{q.prompt}</p><small>{q.rationale}</small></div><div className="scale" role="group" aria-label={q.category}>{[1,2,3,4,5,6,7,8,9,10].map(n=><button type="button" key={n} aria-pressed={v===n} className={v===n?"selected":""} onClick={()=>setAnswers(a=>({...a,[q.id]:n}))}>{n}</button>)}</div><div className="scale-labels"><span>1 · Significant preparation needed</span><span>5 · Discussion needed</span><span>10 · Strong alignment</span></div></section>})}<div className="form-footer"><span>{Object.keys(answers).length} of 10 domains rated</span><button type="submit">Generate readiness assessment →</button></div></form></main>;
}
