import { SiteHeader, SiteFooter } from "../../components/SiteChrome";
export const metadata={title:"Data Protection"};
export default function DataProtection(){return <main><SiteHeader/><article className="legal-page"><p className="kicker">MWAMBO · DATA PROTECTION</p><h1>Data Protection</h1><p className="legal-lead">Mwambo's data protection approach is built around purpose limitation, data minimisation, security, transparency and respect for the rights of people whose information we process.</p><p className="legal-updated">Last updated: 23 September 2026</p>
<section><h2>1. Our data protection commitment</h2><p>Mwambo aims to process personal data fairly, lawfully and transparently. We seek to collect information for defined purposes, limit access to authorised persons and systems, and avoid collecting information that is not needed.</p></section>
<section><h2>2. Personal and sensitive personal data</h2><p>Personal data can include information that identifies or can reasonably identify an individual, including names, contact details, online identifiers and location information. Zambian law also recognises categories of sensitive personal data. Information relating to marital status, health, religion, ethnicity and other protected matters may require heightened safeguards.</p></section>
<section><h2>3. Data used by the readiness assessment</h2><p>The marriage readiness assessment is a self-reflection tool and is not a diagnostic service. Results should not be treated as a professional determination of whether someone should marry. Mwambo will design storage and access around the actual function being provided and will avoid retaining assessment information where retention is not necessary.</p></section>
<section><h2>4. Data minimisation</h2><p>Where a feature can operate without identifying a person, Mwambo should prefer that approach. Optional information should be clearly distinguished from information that is necessary to provide a service.</p></section>
<section><h2>5. Access and confidentiality</h2><p>Access to personal information should be limited according to role and operational need. Information should not be disclosed merely because it is available to a system administrator or service provider.</p></section>
<section><h2>6. Service providers</h2><p>Mwambo may use trusted technology providers for hosting, authentication, databases, communications and other infrastructure. Where a provider processes personal data on Mwambo's behalf, appropriate contractual, technical and organisational safeguards should be applied.</p></section>
<section><h2>7. Security and incident response</h2><p>Security measures may include access controls, authentication, encryption where appropriate, secure configuration, logging and controlled administrative access. Where a personal data incident occurs, Mwambo will assess and respond in accordance with applicable legal and regulatory requirements.</p></section>
<section><h2>8. Data subject requests</h2><p>People whose personal data is processed may have rights under applicable law, including rights to access, correct, object to certain processing, restrict processing, request portability and request erasure. Some rights are subject to lawful exceptions.</p></section>
<section><h2>9. Third-party links</h2><p>Mwambo may link to external websites or resources, including published cultural and institutional sources. Once you leave Mwambo, the external service's own privacy and data protection practices apply.</p></section>
<section><h2>10. Governance</h2><p>Mwambo will review its data practices as the platform develops, particularly when new accounts, assessments, communications, analytics or other data-processing features are introduced.</p></section>
<div className="legal-reference"><strong>Zambian framework</strong><p>The Data Protection Act, 2021 establishes the framework for the collection, use, transmission, storage and other processing of personal data in Zambia and provides rights for data subjects. Mwambo's controls should be reviewed as the platform's actual processing activities evolve.</p></div>
</article><SiteFooter/></main>}